import * as v from 'valibot';

export type MostTrackedFlight = v.InferOutput<typeof areaFlightSchema>;

export const mostTrackedFlightSchema = v.object({
  _type: v.optional(v.literal('tracked'), 'tracked'),
  id: v.string(),
  flight_number: v.nullable(v.string()),
  callsign: v.nullable(v.string()),
  squawk: v.nullable(v.string()),
  clicks: v.number(),
  airport_origin_code_iata: v.nullable(v.string()),
  airport_origin_city: v.nullable(v.string()),
  airport_destination_code_iata: v.nullable(v.string()),
  airport_destination_city: v.nullable(v.string()),
  aircraft_code: v.string(),
  aircraft_model: v.string(),
  on_ground: v.nullable(v.number()),
});

export type AreaFlight = v.InferOutput<typeof areaFlightSchema>;

export const areaFlightSchema = v.object({
  _type: v.optional(v.literal('area'), 'area'),
  id: v.string(),
  flight_number: v.nullable(v.string()),
  callsign: v.nullable(v.string()),
  aircraft_registration: v.nullable(v.string()),
  aircraft_photo_small: v.nullable(v.string()),
  aircraft_photo_medium: v.nullable(v.string()),
  aircraft_photo_large: v.nullable(v.string()),
  aircraft_model: v.string(),
  aircraft_code: v.string(),
  airline: v.nullable(v.string()),
  airline_short: v.nullable(v.string()),
  airline_iata: v.nullable(v.string()),
  airline_icao: v.nullable(v.string()),
  airport_origin_name: v.nullable(v.string()),
  airport_origin_code_iata: v.nullable(v.string()),
  airport_origin_code_icao: v.nullable(v.string()),
  airport_origin_country_name: v.nullable(v.string()),
  airport_origin_country_code: v.nullable(v.string()),
  airport_origin_city: v.nullable(v.string()),
  airport_origin_timezone_offset: v.nullable(v.number()),
  airport_origin_timezone_abbr: v.nullable(v.string()),
  airport_origin_terminal: v.nullable(v.string()),
  airport_origin_latitude: v.nullable(v.number()),
  airport_origin_longitude: v.nullable(v.number()),
  airport_destination_name: v.nullable(v.string()),
  airport_destination_code_iata: v.nullable(v.string()),
  airport_destination_code_icao: v.nullable(v.string()),
  airport_destination_country_name: v.nullable(v.string()),
  airport_destination_country_code: v.nullable(v.string()),
  airport_destination_city: v.nullable(v.string()),
  airport_destination_timezone_offset: v.nullable(v.number()),
  airport_destination_timezone_abbr: v.nullable(v.string()),
  airport_destination_terminal: v.nullable(v.string()),
  airport_destination_latitude: v.nullable(v.number()),
  airport_destination_longitude: v.nullable(v.number()),
  time_scheduled_departure: v.nullable(v.number()),
  time_scheduled_arrival: v.nullable(v.number()),
  time_real_departure: v.nullable(v.number()),
  time_real_arrival: v.nullable(v.number()),
  time_estimated_departure: v.nullable(v.number()),
  time_estimated_arrival: v.nullable(v.number()),
  latitude: v.number(),
  longitude: v.number(),
  altitude: v.number(),
  heading: v.number(),
  ground_speed: v.number(),
  squawk: v.string(),
  vertical_speed: v.number(),
  distance: v.number(),
  closest_distance: v.optional(v.number()),
  on_ground: v.nullable(v.number()),
  tracked_by_device: v.string(),
});
